// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr1sxNKTZhQgQMYp4Z62J135huL8lo_sQ',
    appId: '1:214879514019:web:256e79079621e6898c7e16',
    messagingSenderId: '214879514019',
    projectId: 'pbl-jawara-1f60b',
    authDomain: 'pbl-jawara-1f60b.firebaseapp.com',
    storageBucket: 'pbl-jawara-1f60b.firebasestorage.app',
    measurementId: 'G-0WE4FZB0FX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xD-suou939vzjXEGXbEqMu0-5jsvuOM',
    appId: '1:214879514019:android:f6576021645cd2ef8c7e16',
    messagingSenderId: '214879514019',
    projectId: 'pbl-jawara-1f60b',
    storageBucket: 'pbl-jawara-1f60b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4E8aAEshZ2rEZl4cZJ4eKCM2o50Qpk0k',
    appId: '1:214879514019:ios:608c939d4db6af678c7e16',
    messagingSenderId: '214879514019',
    projectId: 'pbl-jawara-1f60b',
    storageBucket: 'pbl-jawara-1f60b.firebasestorage.app',
    iosBundleId: 'com.example.jawaraPintarKel5',
  );
}
